server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/javascript,application/javascript,text/css,text/plain,text/json,application/json
    min-response-size: 1024
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    threads:
      io: 2
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 20
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /bajie
  port: 8888
#  ssl:
#    key-store: E:\JAVA_Files\Bajie\src\main\resources\keystore.jks
#    key-alias: demo
#    enabled: true
#    key-store-password: bajiechifan
#    key-store-type: JKS


spring:
  web:
    resources:
      #不要为我们工程中的资源文件建立映射
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

   #mysql数据源
  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.234.161:7086/bajie2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: bajiechifan2022
    druid:
      #初始化大小，最小，最大
      initial-size: 10
      max-active: 30
      min-idle: 5
      max-wait: 3000                                           #获取数据库连接等待的超时时间
      max-open-prepared-statements: -1
      time-between-eviction-runs-millis: 60000                 #配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      min-evictable-idle-time-millis: 300000                   #配置连接在池中的最小生存时间
      max-evictable-idle-time-millis: 400000                   #配置连接在池中的最大生存时间
      validation-query: SELECT 1                               #系统启动时通过该sql语句验证数据库是否可用，如果不配置validationQuery，则下面三项无效
      test-while-idle: true                                    #启用空闲连接检测，以便回收
      test-on-borrow: false                                    #从连接池获取连接时，是否检测连接可用性，开启性能会有些许影响
      test-on-return: false                                    #释放连接到连接池时，是否检测连接可用性，开启性能会有些许影响
      pool-prepared-statements: false                          #打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall                                       #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
  #redis
  redis:
    database: 0  #Redis索引0~15，默认为0
    host: 101.33.200.205
    port: 5201
    password: OneDrop@redis
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 300   #连接池最大连接数（使用负值表示没有限制）
        max-wait: 5000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 50     #连接池中的最大空闲连接
        min-idle: 5     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）
  data:
    mongodb:
      uri: mongodb://bajie:bajiechifan2022@114.132.234.161:27017/bajie

  #定时任务
  task:
    scheduling:
      pool:
        size: 1                       # 任务调度线程池大小 默认 1
    execution:
      thread-name-prefix: bajie_        # 调度线程名称前缀 默认 scheduling
      shutdown:
        await-termination: false        # 线程池关闭时等待所有任务完成
        await-termination-period: 10s    # 调度线程关闭前最大等待时间，确保最后一定关闭

mybatis-plus:
  log: true

#请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  #请求连接的超时时间
  ConnectTimeout: 10000
  #eureka客户端ribbon刷新时间
  ServerListRefreshInterval: 3000


multipart:
  max-file-size: 3MB
  max-request-size: 5MB


logging:
  level:
    root: info
#  config: classpath:config/logback-spring.xml

#远程调用okhttp调用
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# 微信配置
wx:
  appid: "wx34f0d8fcaa93e6e0"
  app_secure: "cb6446b98224149ae05ce9e6a98edf7a"

# jwt算法及密码
jwt:
  alg: hs256
  key: bajiechifan

# 不需要登录url路径
secure:
    urls:
      - "/user/login"
      - "/canteen/*"
      - "/dish/*"
      - "/banner/*"
      - "/comment/list"