server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/javascript,application/javascript,text/css,text/plain,text/json,application/json
    min-response-size: 1024
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    threads:
      io: 2
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 20
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /bajie
  port: 8888

spring:
  web:
    resources:
      #不要为我们工程中的资源文件建立映射
      add-mappings: false
  mvc:

    throw-exception-if-no-handler-found: true

    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.234.161:7086/bajie?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: bajiechifan2022
    druid:
      #初始化大小，最小，最大
      initial-size: 10
      max-active: 30
      min-idle: 5
      max-wait: 3000                                           #获取数据库连接等待的超时时间
      max-open-prepared-statements: -1
      time-between-eviction-runs-millis: 60000                 #配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      min-evictable-idle-time-millis: 300000                   #配置连接在池中的最小生存时间
      max-evictable-idle-time-millis: 400000                   #配置连接在池中的最大生存时间
      validation-query: SELECT 1                               #系统启动时通过该sql语句验证数据库是否可用，如果不配置validationQuery，则下面三项无效
      test-while-idle: true                                    #启用空闲连接检测，以便回收
      test-on-borrow: false                                    #从连接池获取连接时，是否检测连接可用性，开启性能会有些许影响
      test-on-return: false                                    #释放连接到连接池时，是否检测连接可用性，开启性能会有些许影响
      pool-prepared-statements: false                          #打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall                                       #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
mybatis-plus:
  log: false

#请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  #请求连接的超时时间
  ConnectTimeout: 10000
  #eureka客户端ribbon刷新时间
  ServerListRefreshInterval: 3000


multipart:
  max-file-size: 3MB
  max-request-size: 5MB


logging:
  config: classpath:config/logback-spring.xml

wx:
  appid: "wx34f0d8fcaa93e6e0"
  app_secure: "cb6446b98224149ae05ce9e6a98edf7a"